<?php
/**
 * Note:仅开发环境测试登录
 * User: kkoma
 * Date: 2019/7/18
 * Time: 15:29
 */

namespace frontend\filters;


use common\libs\BaseFilter;
use frontend\models\login\LoginForm;
use frontend\models\school\School;
use Yii;

class LoginFilter extends BaseFilter
{

    public function beforeFilter($event)
    {
        $is_login = Yii::$app->user->isGuest;
        if ($is_login) {
            $check_data['username'] = 'js11';
            $check_data['passwd'] = md5('12345678Aa');
            $login_form = new LoginForm();
            if ($login_form->load($check_data, '') && $login_form->login()) {
                $school = new School();
                //创建session及相应业务操作
                $user = Yii::$app->user->identity;
                $session = Yii::$app->session;
                $authority_token = session_id();
                $cache = Yii::$app->cache;
                //获取用户角色及相应的权限信息
                $cache->set('authority_token-' . $user->id, $authority_token, 10 * 60);
                if (in_array($user->role, [2, 3])) {
                    //数据权限
                    $access = $school->getAccountAccess([
                        'm1.id' => explode(',', $user->controller),
                        'm2.id' => explode(',', $user->action),
                        'm3.id' => explode(',', $user->operation)
                    ]);
                    $session->set('access', $access);
                    //院系专业班级权限账号
                    $session->set('dept', [
                        'department' => explode(',', $user->department),
                        'major' => explode(',', $user->major),
                        'class' => explode(',', $user->class),
                    ]);
                    $session->set('no_authority', 1);
                }
                $cache = Yii::$app->cache;
                $cache->set('default_period' . $user['id'], 2018, 60 * 60);
//            $this->_response([
//                'authority_token' => $authority_token]);
            }
        }

        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }
}